# Generated by Django 4.1.4 on 2023-01-06 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Player_Name', models.CharField(max_length=50)),
                ('Player_Age', models.IntegerField()),
                ('Player_Phno', models.BigIntegerField()),
                ('Player_Game_Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Eightapp.game')),
            ],
        ),
    ]
